### ISSUE TITLE
Templating error

### ISSUE THREAD

**Issue by hansmorb** [StackFocus/ansible-role-postfix-dovecot#13]
Hey, I am getting this error when trying to run the role on Ubuntu focal LTS:

`fatal: [default]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on (# {{ ansible_managed }}\n#\n# # Debian specific:  Specifying a file name will cause the first\n# line of that file to be used as the name.  The Debian default\n# is /etc/mailname.\n\nsmtpd_banner = $myhostname ESMTP $mail_name\nbiff = no\n\n# appending .domain is the MUA's job.\nappend_dot_mydomain = no\n\n# Uncomment the next line to generate \"delayed mail\" warnings\n#delay_warning_time = 4h\n\n# TLS parameters\nsmtpd_tls_cert_file = {{ postfix_ssl_cert }}\nsmtpd_tls_key_file = {{ postfix_ssl_key }}\n\nsmtpd_use_tls = yes\nsmtpd_tls_session_cache_database =\nsmtp_tls_session_cache_database =\n\n# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for\n# information on enabling SSL in the smtp client.\n\nsmtpd_relay_restrictions = {{ postfix_smtpd_relay_restrictions | join(', ') }}\nmyhostname = {{ postfix_myhostname | default(ansible_fqdn) }}\nalias_maps = hash:/etc/aliases\nalias_database = hash:/etc/aliases\nmyorigin = /etc/mailname\nmydestination = {{ postfix_mydestination | join(', ') }}\nrelayhost = {{ postfix_relayhost | default() }}\nmynetworks = {{ postfix_mynetworks | join(' ') }}\nmailbox_size_limit = 0\nrecipient_delimiter = +\ninet_interfaces = all\ninet_protocols = {{ postfix_inet_protocols }}\n\n# Additional parameters\nsmtpd_tls_auth_only = {{ postfix_smtpd_tls_auth_only }}\nsmtpd_sasl_type = dovecot\nsmtpd_sasl_path = private/auth\nsmtpd_sasl_auth_enable = yes\nsmtpd_recipient_restrictions = {{ postfix_smtpd_recipient_restrictions | join(', ') }}\n\nsmtpd_helo_required = yes\nsmtpd_helo_restrictions = {{ postfix_smtpd_helo_restrictions | join(', ') }}\n\nsmtpd_sender_restrictions = {{ postfix_smtpd_sender_restrictions | join(', ') }}\n\nvirtual_transport = lmtp:unix:private/dovecot-lmtp\nvirtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf\nvirtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf\nvirtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf\n\naddress_verify_negative_refresh_time = 60s\naddress_verify_sender_ttl = 15686s\nbroken_sasl_auth_clients = yes\n{% if (ansible_os_family != 'RedHat') and (ansible_distribution_major_version <= 7) %}\ncompatibility_level = 2\n{% endif %}\nhtml_directory = /usr/share/doc/postfix/html\nreadme_directory = /usr/share/doc/postfix\nsmtpd_client_message_rate_limit = {{ postfix_smtpd_client_message_rate_limit }}\nsmtpd_tls_exclude_ciphers = RC4, aNULL\nsmtp_tls_exclude_ciphers = RC4, aNULL\nsmtp_tls_protocols = !SSLv2,!SSLv3\nsmtp_tls_security_level = {{ postfix_smtp_tls_security_level }}\n{% if postfix_smtp_dns_support_level is sameas true %}\nsmtp_dns_support_level = dnssec\n{% endif %}\n): '<=' not supported between instances of 'AnsibleUnsafeText' and 'int'"}`

**Comment by badnetmask** [comment]
That was actually my bad, sorry. I sent a PR with a fix, it needs to be pushed by @thatarchguy.

**Comment by hansmorb** [comment]
Thank you very much, this fixed the issue for me!
