### ISSUE TITLE
ansible_distribution_major_version <= 7 - not supported between instances of 'AnsibleUnsafeText' and 'int'"

### ISSUE THREAD

**Issue by Vitexus** [StackFocus/ansible-role-postfix-dovecot#16]
Hallo, there is problem when with integer cpomparsion.

**Comment by Vitexus** [comment]
Already implementet, but not released yet on galaxy.
Sorry for buzz.

**Comment by mprahl** [comment]
@Vitexus thanks for letting us know. I created a new release with the fix that is now in Ansible Galaxy.
