### ISSUE TITLE
include mysql db schema

### ISSUE THREAD

**Issue by ghost** [StackFocus/ansible-role-postfix-dovecot#4]
For users not interested in running this alongside postmaster, it would be useful to include the MySQL db schema. Currently there are two options for anyone wanting to use this role as a single-hit solution:
1 - Reverse engineer the table structure from all the SQL queries used in the config files in this role
2 - Hunt around for clues as to what the database structure is.

After a few hours of looking around, I finally found out that this role is meant as a supplement to the PostMaster web gui frontend, however even at the PostMaster git repository I could hardly find any clue other than the fact that the software is supposed to ease the administration of a specific setup recommended by two separate tutorials;
For anyone else looking, here's the database schema:

```
CREATE TABLE `virtual_domains` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `virtual_users` (
  `id` int(11) NOT NULL auto_increment,
  `domain_id` int(11) NOT NULL,
  `password` varchar(106) NOT NULL,
  `email` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `virtual_aliases` (
  `id` int(11) NOT NULL auto_increment,
  `domain_id` int(11) NOT NULL,
  `source` varchar(100) NOT NULL,
  `destination` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by mprahl** [comment]
I'm sorry for the late reply. I've added this to the read me.
